### ISSUE TITLE
[BUG]Checkbox not working in reading mode

### ISSUE THREAD

**Issue by ragundo** [Maldonacho/obsidian-encore-theme#2]
**Describe the Bug**
Impossible to check

**Relevant Screenshots**
Encore Theme
![imagen](https://user-images.githubusercontent.com/9405614/180078298-6f92d6ef-5a13-4933-83b5-b60c5471bdf0.png)

Any other Theme (Wasp)
![imagen](https://user-images.githubusercontent.com/9405614/180078380-b6e68d1f-fe55-40ec-89bb-da76a9a8d81a.png)

**To Reproduce**
Steps to reproduce the behavior, e.g.
1. Open a Kanban Board
2. Click on an TODO task, for example
3. It desn't change. DONE task already checked are shown uncheked

**In which mode does the bug occur?**
- [ x] Reading/Preview Mode
- [ ] Source Mode
- [ ] Live Preview

**Which editor are you using?**
- [ ] Legacy Editor
- [x] New Editor

**Which version of Obsidian are you using?**
- [x] Public Release (Desktop)
- [ ] Public Release (Mobile)
- [ ] Insider Release (Desktop)
- [ ] Insider Release (Mobile)

**Checklist**
- [x] I have updated to the latest version of the theme (`Obsidian Settings → Appearance → Themes - Manage → Update`).
- [x] I made sure that the issue is related to this theme, by checking that the issue does not occur with other themes or the default theme.

**Comment by Maldonacho** [comment]
Thanks for the report! I'll make sure this doesn't happen in v1 :)

**Comment by Maldonacho** [comment]
This has been fixed in the latest version
![image](https://user-images.githubusercontent.com/31268463/200154100-cc3a5eeb-6304-4ba8-8e2c-84d3b4095939.png)
