### ISSUE TITLE
Is this still live?

### ISSUE THREAD

**Issue by DutchPete** [Maldonacho/obsidian-encore-theme#3]
I was wondering if you are still working on this wonderful theme?

**Comment by Maldonacho** [comment]
I heard that they were redoing the default theme for v1, so I stopped working on this.
Now it's here, I actually really like it! There are a few things I reckon can be improved still, like embedded notes - I think Encore still does a better job. So this theme still has a purpose.

So in short: Yes, I'll soon be redoing this to make it work with v1 :)
